### ISSUE TITLE
License error message lock out

### ISSUE THREAD

**Issue by school-workshops** [bjohnson045/phpMyDirectory#23]
Just tried to log in to my website but received the following message and cannot proceed. I have important work to complete and I need access. Can you advise what is going on please and sort this issue out promptly

**There was a problem validating your software license.
- Verify your license code is in defaults.php
- Try reissueing your license.

If you still receive problems, please contact support.**

**Comment by USDOOO** [comment]
all sites in the admin part stopped working. Help
PRESIDENTinternet.net

**Comment by bjohnson045** [comment]
@school-workshops @USDOOO phpMyDirectory is now open source. You will need to upload the unencrypted version from Github that no longer includes the license validation code.

**Comment by USDOOO** [comment]
но работает не корректно ? 09.11.2021, 17:26, "Ben Johnson" ***@***.******@***.*** @USDOOO phpMyDirectory is now open source. You will need to upload the unencrypted version from Github that no longer includes the license validation code.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.   -- С уважением,Техническая поддержка,PRESIDENTinternet.ORG

**Comment by USDOOO** [comment]
Is it necessary to update files? Some sites work correctly. Example: https://podarkisochi.com
